In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_moons
from numpy import newaxis



In [7]:
X = X[:10,:]

In [8]:
np.sum(np.square(X-X[3,:]), axis = 1)

array([ 1.59387008,  0.94238922,  0.81885352,  0.        ,  0.06541027,
        1.72634201,  0.39717276,  1.33253313,  1.67944712,  1.24747295])

In [53]:
dist = a[np.newaxis,:,:] - b[:,np.newaxis,:]

c = np.sum(dist**2,axis = 1)

y = np.argmin(c, axis = 1)

dist.shape

In [21]:
b.reshape(-1,1).shape


(5000, 1)

In [2]:
a = np.random.randint(0,5,(5000,13))
b = np.random.randint(0,13,(5000,))

In [87]:
a = a + b[np.newaxis].T

In [98]:
a - a[np.arange(a.shape[0]), b].reshape(-1,1)

array([[-2, -2,  0, ..., -4,  0, -1],
       [ 1, -3, -1, ...,  1,  0, -1],
       [-2,  0,  2, ...,  2, -1,  2],
       ..., 
       [-2, -3, -4, ..., -1,  0, -2],
       [-2, -1, -2, ...,  0,  2,  0],
       [ 3,  0, -1, ...,  2,  1,  1]])

In [10]:
a[:5]

array([[2, 2, 2, 0, 1, 1, 3, 0, 4, 0, 0, 4, 3],
       [3, 0, 1, 2, 0, 3, 4, 4, 0, 2, 3, 0, 0],
       [3, 1, 4, 0, 4, 2, 3, 2, 3, 0, 1, 2, 0],
       [1, 2, 2, 2, 3, 2, 3, 2, 1, 3, 0, 4, 0],
       [3, 2, 0, 1, 4, 4, 3, 4, 2, 3, 1, 1, 0]])

In [96]:
b[:5]

array([5, 7, 1, 2, 3])

In [6]:
a = np.zeros((23,10))
b = np.ones((10,))

In [11]:
np.maximum(3,a)

array([[3, 3, 3, ..., 3, 4, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 4, ..., 3, 3, 3],
       ..., 
       [3, 3, 4, ..., 3, 4, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 4, ..., 3, 3, 3]])

In [6]:
np.sum(a, axis = 0).shape

(13,)

In [5]:
a.shape

(5000, 13)

In [ ]:
np.random.choice()

In [5]:
np.argmax(a, axis = 0).shape

(13,)

In [10]:
k = 4
for i in range(10000):
    k *= 0.999
print k

0.000180693383908
